In [1]:
# SQLite is a lightweight, disk-based database that doesn't require a separate server process.
import sqlite3 as db
import pandas as pd

In [ ]:
con = db.connect('sqlite.db')
## cursor userd to execute SQL commands
cn = con.cursor()

In [3]:
# drop table if exists
cn.execute("DROP TABLE IF EXISTS employees")

In [4]:
cn.execute("CREATE TABLE employees (empid INTEGER PRIMARY KEY, firstname NVARCHAR(50), lastname NVARCHAR(50))")

In [9]:
cn.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cn.fetchall())

[('employees',)]

In [14]:
cn.execute("INSERT OR IGNORE INTO employees VALUES (1, 'John', 'Doe')")
cn.execute("INSERT OR IGNORE INTO employees VALUES (2, 'Jason', 'Hale')")
cn.execute("INSERT OR IGNORE INTO employees VALUES (3, 'Sam', 'Billing')")

In [15]:

cn.execute("SELECT * FROM employees;")
print(cn.fetchall())

[(1, 'John', 'Doe'), (2, 'Jason', 'Hale'), (3, 'Sam', 'Billing')]

In [16]:

new_employees = [(4, 'Gustavo', 'Achong'),
 (5, 'Kim', 'Abercrombie'),
 (6, 'Pilar', 'Bernard'),
 (7, 'Frances', 'Adams'),
 (8, 'Margaret', 'Smith'),
 (9, 'Angela', 'Adams'),
 (10, 'Samuel', 'Agcaoili')]
cn.executemany('INSERT INTO employees VALUES (?, ?, ?)', new_employees)

In [17]:
cn.execute("SELECT * FROM employees;")
print(cn.fetchall())

[(1, 'John', 'Doe'), (2, 'Jason', 'Hale'), (3, 'Sam', 'Billing'), (4, 'Gustavo', 'Achong'), (5, 'Kim', 'Abercrombie'), (6, 'Pilar', 'Bernard'), (7, 'Frances', 'Adams'), (8, 'Margaret', 'Smith'), (9, 'Angela', 'Adams'), (10, 'Samuel', 'Agcaoili')]

In [19]:
con.commit()

In [ ]:
cn.close()
con.close()

In [24]:
con = db.connect('sqlite.db')
df_employees = pd.read_sql_query('select * from employees', con)

In [25]:
df_employees

   empid firstname     lastname
0      1      John          Doe
1      2     Jason         Hale
2      3       Sam      Billing
3      4   Gustavo       Achong
4      5       Kim  Abercrombie
5      6     Pilar      Bernard
6      7   Frances        Adams
7      8  Margaret        Smith
8      9    Angela        Adams
9     10    Samuel     Agcaoili

In [26]:
df_employees.head()

   empid firstname     lastname
0      1      John          Doe
1      2     Jason         Hale
2      3       Sam      Billing
3      4   Gustavo       Achong
4      5       Kim  Abercrombie

In [31]:
df_new = df_employees[:-1]

In [33]:
df_new

   empid firstname     lastname
0      1      John          Doe
1      2     Jason         Hale
2      3       Sam      Billing
3      4   Gustavo       Achong
4      5       Kim  Abercrombie
5      6     Pilar      Bernard
6      7   Frances        Adams
7      8  Margaret        Smith
8      9    Angela        Adams

In [41]:
df_new.to_sql("employees", con, if_exists="replace")

9

In [42]:
pd.read_sql_query ('select * from employees', con)

   index  empid firstname     lastname
0      0      1      John          Doe
1      1      2     Jason         Hale
2      2      3       Sam      Billing
3      3      4   Gustavo       Achong
4      4      5       Kim  Abercrombie
5      5      6     Pilar      Bernard
6      6      7   Frances        Adams
7      7      8  Margaret        Smith
8      8      9    Angela        Adams

In [43]:
con.close()